---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: gpu
spec:
  subnetSelector:
      karpenter.sh/discovery: fmops-cluster
  securityGroupSelector:
      karpenter.sh/discovery: fmops-cluster
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        encrypted: true
  tags:
    managed-by: "karpenter"
    intent: "apps"
    Name: "jupyter-karpenter-node"