apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate-gpu-instance
  namespace: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: gpu   # This is the nodeSelector
      tolerations:   # To tolerate the taint on the nodes
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80