# Default values for gpu-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

daemonsets:
  labels: {}
  annotations: {}
  priorityClassName: system-node-critical
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
    - operator: "Exists" # Added this to ensure it can tolerate any custom Taints added to the GPU nodes

validator:
  repository: nvcr.io/nvidia/cloud-native
  image: gpu-operator-validator

operator:
  repository: nvcr.io/nvidia
  priorityClassName: system-node-critical
  defaultRuntime: containerd
  image: gpu-operator
  cleanupCRD: false # This option doesn't do anything even if you change this to true. NVIDIA recommends to use the manual approach of upgrading the CRDs
  upgradeCRD: false
  resources:
    limits:
      cpu: 500m
      memory: 350Mi
    requests:
      cpu: 200m
      memory: 100Mi

mig:
  strategy: single

# https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/install-precompiled-signed-drivers.html
# Currently NVIDIA Operator takes more than 5 mins to make the node GPU ready with all the required drivers.
# With pre-compiled NVIDIA Drivers this process can be faster hence we are using the config values as driver.version: "515-signed"
driver:
  enabled: true
  repository: nvcr.io/nvidia
  image: driver
  # Commented this as latest Ubuntu AMIs are failing with this option enabled
  # version: "515-signed" # supported DRIVER_BRANCH value currently are 470, 510 and 515 which will install latest drivers available on that branch for current running kernel version.
  manager:
    image: k8s-driver-manager
    repository: nvcr.io/nvidia/cloud-native

toolkit:
  enabled: true

devicePlugin:
  enabled: true
  config:
    name: time-slicing-config-all
    default: any
    create: true
    data:
      any: |-
        version: v1
        flags:
          migStrategy: none
        sharing:
          timeSlicing:
            resources:
            - name: nvidia.com/gpu
              replicas: 4

dcgm:
  enabled: false

dcgmExporter:
  enabled: true

gfd:
  enabled: true

migManager:
  enabled: true

nodeStatusExporter:
  enabled: false

gds:
  enabled: false

vgpuManager:
  enabled: false

vgpuDeviceManager:
  enabled: true

vfioManager:
  enabled: true

sandboxDevicePlugin:
  enabled: true

node-feature-discovery:
  enableNodeFeatureApi: true
  worker:
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      - operator: "Exists" # Added this to ensure it can tolerate any custom Taints added to the GPU nodes