---
apiVersion: v1
kind: Service
metadata:
  name: mistral
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/app-metrics: "true"
    prometheus.io/port: "8080"
  labels:
    model: mistral7b
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    model: mistral7b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mistral
  labels:
    model: mistral7b
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      model: mistral7b
  template:
    metadata:
      labels:
        model: mistral7b
    spec:
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      nodeSelector:
        nvidia.com/gpu.present: "true"
      containers:
        - name: vllm
          image: docker.io/vllm/vllm-openai@sha256:4f4037303e8c7b69439db1077bb849a0823517c0f785b894dc8e96d58ef3a0c2
          imagePullPolicy: IfNotPresent
          args:
            - '--port=8080'
            - '--model=/local-storage/models/mistral-7b-v0-3'
            - '--tokenizer_mode=mistral'
            - '--tokenizer=/local-storage/models/mistral-7b-v0-3'
            - '--gpu_memory_utilization=0.90'
            - '--max-model-len=2048'
            - '--tensor-parallel-size=1'
            - '--max-num-batched-tokens=8192'
            - '--max-num-seqs=256'
            - '--block-size=16'
            - '--enforce-eager'
            - '--swap-space=16'
            - '--disable-custom-all-reduce'
          env:
            - name: CUDA_LAUNCH_BLOCKING
              value: "1"
            - name: PYTORCH_CUDA_ALLOC_CONF
              value: "max_split_size_mb:512"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          resources:
            requests:
              cpu: 6
              memory: 32Gi
              nvidia.com/gpu: 1
            limits:
              cpu: 6
              memory: 32Gi
              nvidia.com/gpu: 1
          volumeMounts:
            - name: local-storage
              mountPath: /local-storage
              readOnly: true
      volumes:
        - name: local-storage
          hostPath:
            path: /local-storage
            type: Directory
