name: default
clusterName:
instanceSizes: ["xlarge", "2xlarge", "4xlarge", "8xlarge", "16xlarge", "24xlarge"]
instanceFamilies: ["c5", "m5", "r5"]
taints:
  - key: hub.jupyter.org/dedicated
    value: "user"
    effect: "NoSchedule"
deviceName: "/dev/xvda" # Default for Amazon Linux
labels:
  hub.jupyter.org/node-purpose: user
amiFamily: AL2