---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: kuberay
spec:
  subnetSelector:
      karpenter.sh/discovery: fmops-cluster
  securityGroupSelector:
      karpenter.sh/discovery: fmops-cluster
  blockDeviceMappings:
    - deviceName: "/dev/xvda" # Device mapped inside node for Ray ML operations
      ebs:
        volumeSize: "1000Gi"
        volumeType: "gp3"
        deleteOnTermination: true
  tags:
    managed-by: "karpenter"
    intent: "apps"
    Name: "kuberay-karpenter-node"